# Generated by Django 5.1 on 2024-09-15 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('respuesta_id', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.CharField(max_length=255)),
                ('opcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opciones.opcion')),
            ],
        ),
    ]
