# Generated by Django 5.1 on 2024-09-17 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiones', '0005_alter_gestion_conversacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestion',
            name='conversacion',
        ),
    ]
