# Generated by Django 5.1 on 2024-10-28 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiones', '0006_remove_gestion_conversacion'),
        ('tipoGestiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='tipo_gestion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tipoGestiones.tipo_gestion'),
        ),
    ]
