# Generated by Django 5.1 on 2024-09-17 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversaciones', '0008_alter_conversacion_usuario'),
        ('gestiones', '0006_remove_gestion_conversacion'),
        ('opciones', '0002_alter_opcion_paso'),
        ('pasos', '0002_alter_paso_gestion'),
        ('respuestas', '0002_alter_respuesta_opcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion_Gestion',
            fields=[
                ('conversacion_gestion_id', models.AutoField(primary_key=True, serialize=False)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='conversaciones.conversacion')),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gestiones.gestion')),
            ],
        ),
        migrations.CreateModel(
            name='Conversacion_Paso',
            fields=[
                ('conversacion_paso_id', models.AutoField(primary_key=True, serialize=False)),
                ('conversacion_gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='conversaciones.conversacion_gestion')),
                ('paso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pasos.paso')),
            ],
        ),
        migrations.CreateModel(
            name='Conversacion_Opcion',
            fields=[
                ('conversacion_opcion_id', models.AutoField(primary_key=True, serialize=False)),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='opciones.opcion')),
                ('conversacion_paso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='conversaciones.conversacion_paso')),
            ],
        ),
        migrations.CreateModel(
            name='Conversacion_Respuesta',
            fields=[
                ('conversacion_respuesta_id', models.AutoField(primary_key=True, serialize=False)),
                ('conversacion_opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='conversaciones.conversacion_opcion')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='respuestas.respuesta')),
            ],
        ),
    ]
