# Generated by Django 5.1 on 2024-10-02 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiones', '0006_remove_gestion_conversacion'),
        ('pasos', '0002_alter_paso_gestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paso',
            name='gestion',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gestiones.gestion'),
        ),
    ]
