# Generated by Django 5.1 on 2024-10-02 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opciones', '0003_opcion_siguiente_paso'),
        ('pasos', '0002_alter_paso_gestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcion',
            name='paso',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pasos.paso'),
        ),
    ]
