# Generated by Django 5.1 on 2024-10-02 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opciones', '0004_alter_opcion_paso'),
        ('pasos', '0003_alter_paso_gestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcion',
            name='siguiente_paso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pasos.paso'),
        ),
    ]
