# Generated by Django 5.1 on 2024-09-17 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversaciones', '0008_alter_conversacion_usuario'),
        ('gestiones', '0002_gestion_conversacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='conversacion',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gestiones', to='conversaciones.conversacion'),
        ),
    ]
