# Generated by Django 5.1 on 2024-09-16 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversaciones', '0007_rename_usuario_id_conversacion_usuario'),
        ('usuarios', '0004_rename_mail_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversacion',
            name='usuario',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
    ]
