# Generated by Django 5.1 on 2024-10-28 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversaciones', '0010_alter_conversacion_usuario'),
        ('tipoGestiones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversacion_gestion',
            name='conversacion',
        ),
        migrations.CreateModel(
            name='Conversacion_Tipo_Gestion',
            fields=[
                ('conversacion_tipo_gestion_id', models.AutoField(primary_key=True, serialize=False)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='conversaciones.conversacion')),
                ('tipo_gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tipoGestiones.tipo_gestion')),
            ],
        ),
        migrations.AddField(
            model_name='conversacion_gestion',
            name='conversacion_tipo_gestion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='conversaciones.conversacion_tipo_gestion'),
            preserve_default=False,
        ),
    ]
