# Generated by Django 5.1 on 2024-10-28 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversaciones', '0011_remove_conversacion_gestion_conversacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversacion_gestion',
            name='conversacion_tipo_gestion',
        ),
        migrations.AddField(
            model_name='conversacion_gestion',
            name='conversacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='conversaciones.conversacion'),
        ),
    ]
