# Generated by Django 5.1 on 2024-09-26 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opciones', '0002_alter_opcion_paso'),
        ('pasos', '0002_alter_paso_gestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcion',
            name='siguiente_paso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opciones_siguientes', to='pasos.paso'),
        ),
    ]
